### ISSUE TITLE
extension's icon is visible and clickable when screen is locked

### ISSUE THREAD

**Issue by massimiliano-dalcero** [b00f/gnome-trash#5]
I use Gnome 42 on Ubuntu 22.04.
When screen is locket (SUPER+L), the extension's icon is visible and clickable. So a unauthorized user can empty trash without permissions.

**Comment by b00f** [comment]
@massimiliano-dalcero Thanks for reporting it. I will check how we can prevent showing on the locked screen.

**Comment by b00f** [comment]
Looks it is not easy to address this issue: https://stackoverflow.com/questions/47008276/gnome-shell-extensions-preventing-the-call-of-disable-when-the-screen-gets-lo

**Comment by b00f** [comment]
It's fixed [here](https://github.com/b00f/gnome-trash/commit/deeaea7dce10d08ebadc64977e8857d706f41c8b) 
@massimiliano-dalcero 
Please update the extension and close this issue if it is fixed there

**Comment by massimiliano-dalcero** [comment]
Tested and fixed :)
